### (x.com/@7etsuo) - 2024 ###
#  ▄▄▄█████▓▓█████▄▄▄█████▓  ██████  █    ██  ▒█████  
#  ▓  ██▒ ▓▒▓█   ▀▓  ██▒ ▓▒▒██    ▒  ██  ▓██▒▒██▒  ██▒
#  ▒ ▓██░ ▒░▒███  ▒ ▓██░ ▒░░ ▓██▄   ▓██  ▒██░▒██░  ██▒
#  ░ ▓██▓ ░ ▒▓█  ▄░ ▓██▓ ░   ▒   ██▒▓▓█  ░██░▒██   ██░
#    ▒██▒ ░ ░▒████▒ ▒██▒ ░ ▒██████▒▒▒▒█████▓ ░ ████▓▒░
#    ▒ ░░   ░░ ▒░ ░ ▒ ░░   ▒ ▒▓▒ ▒ ░░▒▓▒ ▒ ▒ ░ ▒░▒░▒░ 
#      ░     ░ ░  ░   ░    ░ ░▒  ░ ░░░▒░ ░ ░   ░ ▒ ▒░ 
#    ░         ░    ░      ░  ░  ░   ░░░ ░ ░ ░ ░ ░ ▒  
#              ░  ░              ░     ░         ░ ░  
############################################################

[env]
TERM = "xterm-256color"

[window]
decorations = "none"
startup_mode = "Maximized"
dynamic_title = true
opacity = 1.0

[scrolling]
history = 10000
multiplier = 3

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[colors.normal]
black   = "#282828"
red     = "#cc241d"
green   = "#98971a"
yellow  = "#d79921"
blue    = "#458588"
magenta = "#b16286"
cyan    = "#689d6a"
white   = "#a89984"

[colors.bright]
black   = "#928374"
red     = "#fb4934"
green   = "#b8bb26"
yellow  = "#fabd2f"
blue    = "#83a598"
magenta = "#d3869b"
cyan    = "#8ec07c"
white   = "#ebdbb2"

[colors.cursor]
text = "#282828"
cursor = "#d65d0e"

[cursor]
style = { shape = "Block", blinking = "On" }
vi_mode_style = "Block"
unfocused_hollow = true
thickness = 0.15

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
{ key = "V",        mods = "Control|Shift", action = "Paste"            },
{ key = "C",        mods = "Control|Shift", action = "Copy"             },
{ key = "Insert",   mods = "Shift",         action = "PasteSelection"   },
{ key = "Key0",     mods = "Control",       action = "ResetFontSize"    },
{ key = "Equals",   mods = "Control",       action = "IncreaseFontSize" },
{ key = "Minus",    mods = "Control",       action = "DecreaseFontSize" },
{ key = "F11",      action = "ToggleFullscreen"                         },
{ key = "PageUp",   mods = "Shift",         action = "ScrollPageUp"     },
{ key = "PageDown", mods = "Shift",         action = "ScrollPageDown"   },
{ key = "Home",     mods = "Shift",         action = "ScrollToTop"      },
{ key = "End",      mods = "Shift",         action = "ScrollToBottom"   },
    #    { key = "N",        mods = "Control|Shift", action = "SpawnNewInstance" },
    #    { key = "F",        mods = "Control|Shift", action = "SearchForward"    },
    #    { key = "B",        mods = "Control|Shift", action = "SearchBackward"   },
    #    { key = "C",        mods = "Control|Shift", action = "ClearSelection"   },
    #    { key = "V",        mods = "Control|Shift", action = "ToggleViMode"     }
]
