import = ["/home/storm/.config/alacritty/theme.toml"]

[env]
TERM = "alacritty"

[font]
builtin_box_drawing = true
size = 14.0

[font.bold]
family = "Fira Code"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Fira Code"
style = "Italic"

[font.normal]
family = "Fira Code"
style = "Regular"

[window]
decorations = "full"
decorations_theme_variant = "None"
dynamic_title = true
opacity = 0.8
